### ISSUE TITLE
site map is not working

### ISSUE THREAD

**Issue by lkuiucsb** [sbclter/sbclter-website-2019#68]
map: https://sbclter.msi.ucsb.edu/research/sampling_sites/

The warning message said something wrong with the JavaScript

**Comment by mobb** [comment]
It works fine. Someone copied over a file that did not contain the API key.  Possibly, someone changed a group of pages in bulk, instead of just a few. 

This is a snippet of the page that should not have been copied over  (research/sampling_sites/index.html): 
![Screen Shot 2020-02-04 at 9 32 30 AM](https://user-images.githubusercontent.com/4931977/73770457-50a23a00-4731-11ea-8058-d652872494d0.png)

Pointers:
1. if you do a bulk copy, be sure that every page works on your localhost before you copy. Alternatively, since you will have already checked the pages you changed on localhost, only copy those.

2. The API key must NEVER go into git. So you must read the instructions in the `_config.yml` file. 

3. @lkuiucsb: The message from the page was `look at the javascript console`. There was no error in the javascript, but the console said the API key was wrong. Li, you should get the web developer add-on. It includes a javascript console, and the problem was quite obvious when I opened it up.
